sudo: required
services:
  - docker
  before_install:
    - openssl aes-256-cbc -K $encrypted_9f3b5599b056_key -iv $encrypted_9f3b5599b056_iv -in service-account.json.enc -out service-account.json -d
    - curl https://skd.cloud.google.com | bash > /dev/null;
    - source $HOME/google-cloud-sdk/path.bash.inc
    - gcloud components update kubectl
    - gcloud auth activate-service-account --key-file service-account.json
    - gcloud config set project fibonacci-kubernates
    - gcloud config set complete/zone us-central1-a
    - gcloud container clusters get-credentials fibonacci-cluster
    - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_USERNAME" --password-stdin
    - docker build -t kacperKwiatkowski/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run kacperKwiatkowski/react-test npm test -- --coverage